### ISSUE TITLE
Simplifier la camera

### ISSUE THREAD

**Issue by FXRoux** [atompacman/Xerof#21]
Sortir tout ce qui attrait à l'affichage de la camera, et ne garder que des caractéristique comme le niveau de zoom, la position et l'orientation de la camera dans la classe camera
Ceci permettra aussi de simplement modifier la position de la camera relativement au déplacement de la souris, ou encore au deplacement du personnage
Et l'affichage qui lui questionne la camera réalisera alors d'une frame à l'autre que les attribut change et n'aura qu'a redessiner en conséquent, ou lorsque set position, set zoom, ou set rotation sera appellé, il ne s'agira que de faire appelle à update display

**Comment by atompacman** [comment]
Constants about textures have been moved to Parameters.h

**Comment by atompacman** [comment]
Mouse and Keyboard classes now update a "DisplayInfo" object that is used by the Display class to draw the display properly.
