### ISSUE TITLE
Verify State Mouse & Verify State Keyboard

### ISSUE THREAD

**Issue by FXRoux** [atompacman/Xerof#22]
Sortir les vérification comme est-ce que tel bouton est down, du gameloop et tous les regrouper dans leur composante, et ne faire appelle à VerifyState de mouse qu'une seul fois
Et advenant qu'un des bouton soit utilisé mouse appellera les méthodes nécessaire à l'execution de l'action désiré

**Comment by Feroxius** [comment]
Pour le clavier il serait préférable de vérifier, s'il y a un bouton down et si oui de trouver lequelle, plutot que de vérifier si un bouton est directement appuyé, comme escape

**Comment by atompacman** [comment]
On ne peut pas enlever le switch dans le gameloop car il est appelé **plusieurs fois par frames** et donc ça sera un énorme ralentissement de passer chaque event à chaque composant existant pour que 99% du temps, le composant ne s'en sert pas. La Mouse gère plus en détail cet event, si tu regarde la méthode `void Mouse::handleMouseEvent(const ALLEGRO_EVENT& event)`

**Comment by FXRoux** [comment]
Dans ce cas pourquoi ne pas faire appelle à la fonction handleMouseEvent quand une touche est appuyé, même chose pour le clavier, comme sa au moins on aurait pas le keyboard dans le gameloop, on aurait seulement la verification de si une key est down

**Comment by atompacman** [comment]
Ce que tu dis c'est exactement ce qu'on fait déjà. Par contre, on peut pas faire appel au Keyboard sans avoir l'instance du Keyboard dans la classe.

**Comment by FXRoux** [comment]
Ce que je vois c'est qu'on regarde si escape est down dans le gameloop si je veux ajouter f pour follow sa devrait être dans le clavier
